# Generated by Django 4.2.7 on 2023-12-13 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_webpage_gmail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessRecord',
        ),
    ]
